### ISSUE TITLE
New bounty

### ISSUE THREAD

**Issue by BenAlthauser** [BenAlthauser/tipit-github#169]
Opening a new bounty @tipitbot bounty 2 heart

**Comment by MarkStair** [comment]
@tipitbot bounty 1 joy testing2

**Comment by MarkStair** [comment]
@tipitbot bounty 1 joy testing 12:26

**Comment by BenAlthauser** [comment]
I'll add to the bounty @tipitbot bounty 2 heart

**Comment by BenAlthauser** [comment]
@tipitbot bounty 2 heart

**Comment by BenAlthauser** [comment]
@tipitbot bounty 3 gmbl test bounty

**Comment by BenAlthauser** [comment]
@tipitbot @MarkStair +3 heart

**Comment by BenAlthauser** [comment]
@tipitbot @MarkStair +3 heart

**Comment by BenAlthauser** [comment]
@tipitbot @MarkStair +3 heart

**Comment by BenAlthauser** [comment]
@tipitbot @MarkStair +3 heart

**Comment by BenAlthauser** [comment]
@tipitbot @MarkStair 3 heart

**Comment by BenAlthauser** [comment]
@tipitbot @BenAlthauser 2 heart

**Comment by BenAlthauser** [comment]
@tipitbot @BenAlthauser 2 heart

**Comment by BenAlthauser** [comment]
@tipitbot @BenAlthauser 2 heart

**Comment by BenAlthauser** [comment]
@tipitbot @BenAlthauser 3 heart

**Comment by BenAlthauser** [comment]
@tipitbot @BenAlthauser 3 heart

**Comment by BenAlthauser** [comment]
@tipitbot @BenAlthauser 3 heart

**Comment by BenAlthauser** [comment]
@tipitbot @BenAlthauser +3 heart

**Comment by BenAlthauser** [comment]
@tipitbot @MarkStair +3 heart

**Comment by BenAlthauser** [comment]
@tipitbot @BenAlthauser +3 heart

**Comment by BenAlthauser** [comment]
@tipitbot @BenAlthauser +3 heart

**Comment by BenAlthauser** [comment]
@tipitbot @BenAlthauser +3 heart

**Comment by BenAlthauser** [comment]
@tipitbot @MarkStair +3 heart

**Comment by BenAlthauser** [comment]
@tipitbot @BenAlthauser +3 heart

**Comment by BenAlthauser** [comment]
@tipitbot @BenAlthauser +3 heart

**Comment by BenAlthauser** [comment]
@tipitbot @BenAlthauser +3 heart

**Comment by BenAlthauser** [comment]
@tipitbot @MarkStair +3 heart

**Comment by BenAlthauser** [comment]
@tipitbot @MarkStair +3 heart

**Comment by BenAlthauser** [comment]
@tipitbot @MarkStair +3 heart

**Comment by BenAlthauser** [comment]
this is a test .tip @MarkStair 3 heart tip tip tip

**Comment by BenAlthauser** [comment]
this is just a test .tip @MarkStair 2 heart

**Comment by BenAlthauser** [comment]
<a target="_blank" href="https://www.google.com">google.com</a>

**Comment by BenAlthauser** [comment]
test tip .tip @MarkStair 2 heart

**Comment by BenAlthauser** [comment]
this is a test tip .tip @MarkStair .tip 3 heart

**Comment by BenAlthauser** [comment]
test tip .tip @MarkStair 3 heart this is a memo test

**Comment by BenAlthauser** [comment]
this is a tip test .tip @MarkStair 3 heart memo

**Comment by BenAlthauser** [comment]
.tip @MarkStair 1 JOY

**Comment by BenAlthauser** [comment]
.tip @MarkStair .01 joy

**Comment by BenAlthauser** [comment]
.tip @MarkStair 1 joy

**Comment by BenAlthauser** [comment]
.tip @MarkStair 1 joy

**Comment by BenAlthauser** [comment]
.tip @MarkStair 1 joy
