### ISSUE TITLE
Need to fix the registration script

### ISSUE THREAD

**Issue by BenAlthauser** [BenAlthauser/tipit-github#203]
Hi everyone, the user reg system really needs to be fixed on line 32 .pool 3 heart I hope someone can fix this.

**Comment by falkon303** [comment]
.pool 1 heart I'll add to that pool!

**Comment by BenAlthauser** [comment]
.pool 2 heart

**Comment by falkon303** [comment]
I'll add to the bounty! .pool 3 heart let's get this fixed everyone!

**Comment by BenAlthauser** [comment]
.pool 1 heart

**Comment by falkon303** [comment]
.pool 1 heart

**Comment by BenAlthauser** [comment]
.pool 3 bounty

**Comment by BenAlthauser** [comment]
.pool 3 heart test

**Comment by falkon303** [comment]
.pool 2 heart
