### ISSUE TITLE
Pool to be paid out for fix

### ISSUE THREAD

**Issue by BenAlthauser** [BenAlthauser/tipit-github#260]
There will be a 4 heart reward for fixing this code .pool 4 heart

**Comment by BenAlthauser** [comment]
.pool 4 heart

**Comment by MarkStair** [comment]
.pool 1 poop testing

**Comment by MarkStair** [comment]
.pool 1 poop testing

**Comment by BenAlthauser** [comment]
.pool 2 heart

**Comment by MarkStair** [comment]
.pool 1 poop what happens if closed?

**Comment by MarkStair** [comment]
.tip @BenAlthauser 1 Joy tipit github is great!!!

**Comment by BenAlthauser** [comment]
.pool 2 heart

**Comment by MarkStair** [comment]
.pool 1 joy yes
